version: "3.9"
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - ollama

volumes:
  ollama-data:
